---
title: "hw3"
author: "Yanran"
date: '2023-11-14'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rstan)
library(ggpubr)
library(shinystan)
library(cowplot)
library(devtools)
library(psych)
library(rstudioapi)
library (car)
library(brms)
library(pscl)

current_path <- getActiveDocumentContext()$path
setwd(dirname(current_path))

```

```{r extract datd}

############################################################################
## Example 2: Download and import the transport file through R             #
############################################################################

# Download NHANES 2015-2016 to temporary file    
# download.file("https://wwwn.cdc.gov/nchs/nhanes/2015-2016/DEMO_I.XPT", tf <- tempfile(), mode="wb")
# 
# # Create Data Frame From Temporary File
# DEMO_I3 <- foreign::read.xport(tf)
#     
# # save as an R data frame
# # TutorialUser: update the file path here to a directory where you want to save the data frame 
# saveRDS(DEMO_I3, file="C:\\NHANES\\DATA\\DEMO_I.rds")    
```



```{r load data}
ts <- readRDS("./data/ts_heatindex_heatwarnings_byFIPS_2006_2016.rds")
# extract year
ts$year <- year(ts$Date)


county_pm25 <- read_csv("./data/confounder/county_pm25.csv")
temp_seasonal_county <-  read_csv("./data/confounder/temp_seasonal_county.csv")
temp_seasonal_county$fips <- as.double(temp_seasonal_county$fips)
brfss_county_interpolated <- read_csv("./data/confounder/brfss_county_interpolated.csv")
census_county_interpolated <- read_csv("./data/confounder/census_county_interpolated.csv")

# merge the two data sets
ts_wconf <- ts %>% full_join(county_pm25, by = c("StateCounty_FIPS" = "fips" , "year" = "year")) %>%
  full_join(temp_seasonal_county, by = c("StateCounty_FIPS" = "fips" , "year" = "year")) %>%
  full_join(brfss_county_interpolated, by = c("StateCounty_FIPS" = "fips" , "year" = "year")) %>%
  full_join(census_county_interpolated, by = c("StateCounty_FIPS" = "fips" , "year" = "year")) %>%
  mutate(weekday = wday(Date, week_start=1),
         weekday = ifelse(weekday<6, 1, 0))


View(head(ts_wconf,20))
```

```{r save data}


#saveRDS(ts_wconf, file="ts_wconf.RDS")

# Read the data from the .RDS file
df_read <- readRDS("ts_wconf.RDS")

# Print the data
#print(df_read)
ts_2007 <- df_read %>% filter(year == 2007)

# NA
ts_2007 <- ts_2007 %>% mutate(HImaxF_PopW = ifelse(is.na(HImaxF_PopW), 0, HImaxF_PopW),
                              pm25 = ifelse(is.na(pm25), 0, pm25),
                              alert = ifelse(is.na(alert), 0, alert))

# select columns
ts_2007 <- ts_2007 %>% select(alert, HImaxF_PopW, pm25, mean_bmi, weekday)

# NA
ts_2007 <- ts_2007 %>% mutate(mean_bmi = ifelse(is.na(mean_bmi), 0, mean_bmi)) %>% 
  mutate(weekday = ifelse(is.na(weekday), 0, weekday))





```




