---
title: "hw2"
author: "Yanran"
date: '2023-11-02'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rstan)
library(ggpubr)
library(shinystan)
library(cowplot)
library(devtools)
library(psych)
library(rstudioapi)

current_path <- getActiveDocumentContext()$path
setwd(dirname(current_path))

```


```{r lab_data}
dilution_standards_data <- tibble::tribble(
  ~conc, ~dilution, ~y,
  2000, 1, c(2.341, 2.47),
  667, 1 / 2, c(2.308, 2.243),
  222, 1 / 4, c(1.95, 1.955),
  74.1, 1 / 8, c(0.975, 0.961),
  25, 1 / 16, c(0.302, 0.307),
  8.23, 1 / 32, c(0.111, 0.112),
  2.74, 1 / 64, c(0.068, 0.07),
  0, 0, c(0.058, 0.062),
) %>%
  mutate(rep = purrr::map(conc, ~ c("a", "b"))) %>%
  unnest(c(y, rep))

knitr::kable(dilution_standards_data)

data_plot <- dilution_standards_data %>%
  ggplot(aes(x = conc, y = y, color = rep)) +
  geom_line(alpha = 0.5, linetype = 2) +
  geom_point(alpha = 0.8) +
  scale_x_continuous(expand = expansion(c(0, 0.02)), limits = c(0, NA)) +
  scale_y_continuous(expand = expansion(c(0, 0.02)), limits = c(0, NA)) +
  scale_color_brewer(type = "qual", palette = "Set1") +
  theme(
    legend.position = c(0.8, 0.2),
    legend.background = element_blank()
  ) +
  labs(
    x = "concentration",
    y = "y",
    title = "",
    color = "replicate"
  )

data_plot


```




```{r }
dilution <- read.csv("reconstructed.csv", header = FALSE)
# store in a long vector
dilution <- as.vector(t(dilution))
# hist(dilution, breaks = 30)

ggplot(data.frame(dilution), aes(x = dilution)) +
  geom_histogram(binwidth = 0.125, color = "b", fill = "light blue") +
  theme_minimal() +
  labs(title = "Histogram of signal response", y = "Frequency", x = "Signal response")

```


```{r gibbs}
# Gibbs Sampler for Gaussian Mixture Model
gibbs_gmm <- function(data, K, iter){
  n <- length(data)
  z <- sample(1:K, n, replace = TRUE)
  mu <- rnorm(K, mean(data), sd(data))
  sigma <- rep(sd(data), K)
  logLikelihood <- numeric(iter)
  
  for (t in 1:iter){
    # Sample z
    for (i in 1:n){
      p_z <- numeric(K)
      for (k in 1:K){
        p_z[k] <- dnorm(data[i], mean = mu[k], sd = sigma[k])
      }
      p_z <- p_z / sum(p_z)
      z[i] <- sample(1:K, 1, prob = p_z)
    }
    
    # Sample mu and sigma
    for (k in 1:K){
      data_k <- data[z == k]
      n_k <- length(data_k)
      mu[k] <- rnorm(1, mean(data_k), sqrt(sigma[k]^2/n_k))
      sigma[k] <- sqrt(1 / rgamma(1, shape = n_k/2, rate = sum((data_k - mu[k])^2)/2))
    }
    
    logLikelihood[t] <- sum(sapply(1:n, function(i) log(sum(sapply(1:K, function(k) dnorm(data[i], mean = mu[k], sd = sigma[k]))))))
  }
  
  return(list(z = z, mu = mu, sigma = sigma, logLikelihood = logLikelihood))
}

K <- 2   # Number of clusters
iter <- 1000   # Number of iterations
results <- gibbs_gmm(dilution, K, iter)

```


```{r check convergence}
ggplot(data.frame(results$logLikelihood), aes(x = 1:length(results$logLikelihood), y = results$logLikelihood)) +
  geom_line(color = "blue") +
  theme_minimal() +
  labs(y = "Log Joint Probability", x = "Iteration")


# dilution$cluster <- factor(results$z)
# 
# ggplot(dilution, aes(x = conc, y = y, color = cluster)) +
#   geom_point(size = 2) +
#   labs(title = 'Gaussian Mixture Model Clustering',
#        x = 'Concentration',
#        y = 'Response',
#        color = 'Cluster') +
#   theme_minimal()

```




```{r VI}
elbo_values <- numeric(iter)

# Initialize
phi <- matrix(0.5, nrow = length(dilution), ncol = 2) 
mu <- runif(2, min(dilution), max(dilution)) 
sigma_sq <- rep(1, 2) 
epsilon <- 1e-10  

for (it in 1:iter) {
  # E-step: Update q(z)
  for (i in 1:length(dilution)) {
    for (k in 1:2) {
      log_rho <- log(0.5) + dnorm(dilution[i], mean = mu[k], sd = sqrt(sigma_sq[k] + epsilon), log = TRUE)
      phi[i, k] <- exp(log_rho)
    }
    phi[i, ] <- phi[i, ] / (sum(phi[i, ]) + epsilon)
  }
  
  # M-step: Update mu & sigma2
  for (k in 1:2) {
    mu[k] <- sum(phi[, k] * dilution) / (sum(phi[, k]) + epsilon)
    sigma_sq[k] <- sum(phi[, k] * (dilution - mu[k])^2) / (sum(phi[, k]) + epsilon)
  }

  elbo <- 0
  for (i in 1:length(dilution)) {
    for (k in 1:2) {
      elbo <- elbo + phi[i, k] * (log(0.5) + dnorm(dilution[i], mean = mu[k], sd = sqrt(sigma_sq[k] + epsilon), log = TRUE) - log(phi[i, k] + epsilon))
    }
  }
  elbo_values[it] <- elbo}


ggplot(data.frame(Iteration = 1:iter, ELBO = elbo_values), aes(x = Iteration, y = ELBO)) +
  geom_line() +
  theme_minimal() +
  labs(y = "ELBO", x = "Iteration")

```





